const translations = {
    fr: {
        // Navigation
        "Plats principaux": "Plats principaux",
        "Fondue": "Fondue",
        "Menu Midi": "Menu Midi",
        
        // Filtres
        "Tous": "Tous",
        "Poissons": "Poissons",
        "Viandes": "Viandes",
        "Légumes": "Légumes",
        "Soupes": "Soupes",
        "Riz": "Riz",
        
        // Catégories
        "Poissons & Fruits de Mer": "Poissons & Fruits de Mer",
        "Viandes & Volaille": "Viandes & Volaille",
        "Légumes & Tofu": "Légumes & Tofu",
        "Soupes & Nouilles": "Soupes & Nouilles",
        "Riz & Raviolis": "Riz & Raviolis",

        // Plats
        "Bar grillé à la sauce piquante": "Bar grillé à la sauce piquante",
        "Choucroute de poisson": "Choucroute de poisson",
        "Intestins et poisson": "Intestins et poisson",
        "Poisson bouilli au piment et poivre": "Poisson bouilli au piment et poivre",
        "Crevettes épicées": "Crevettes épicées",
        "Couteaux de mer à l'huile d'oignons verts": "Couteaux de mer à l'huile d'oignons verts",
        "Calamars et crevettes au sel et poivre": "Calamars et crevettes au sel et poivre",
        "Calamars sautés avec légumes": "Calamars sautés avec légumes",
        "Cuisses de poulet entières grillées": "Cuisses de poulet entières grillées",
        "Marmite de bœuf": "Marmite de bœuf",
        "Spécialité de Sichuan (épicé)": "Spécialité de Sichuan (épicé)",
        "Pieds de cochon braisés": "Pieds de cochon braisés",
        "Pot de tendon de bœuf": "Pot de tendon de bœuf",
        "Pot d'agneau": "Pot d'agneau",
        "Porc frit à la sauce aigre-douce": "Porc frit à la sauce aigre-douce",
        "Intestins de porc au piment fort": "Intestins de porc au piment fort",
        "Porc déchiqueté à la sauce d'ail": "Porc déchiqueté à la sauce d'ail",
        "Poulet épicé": "Poulet épicé",
        "Poulet sauce aigre-douce": "Poulet sauce aigre-douce",
        "Assortiment de légumes du marché": "Assortiment de légumes du marché",
        "Mapo Tofu (épicé)": "Mapo Tofu (épicé)",
        "Aubergine à l'ail": "Aubergine à l'ail",
        "Feuilles de tofu au poivre": "Feuilles de tofu au poivre",
        "Zizania avec porc": "Zizania avec porc",
        "Luffa avec edamames": "Luffa avec edamames",
        "Chou blanc sauté": "Chou blanc sauté",
        "Haricots verts sautés": "Haricots verts sautés",
        "Mala Tang (bœuf, agneau, légumes et viandes épicés)": "Mala Tang (bœuf, agneau, légumes et viandes épicés)",
        "Soupe pékinoise": "Soupe pékinoise",
        "Soupe aux tomates et aux œufs": "Soupe aux tomates et aux œufs",
        "Soupe aux raviolis de feuilles de tofu au porc": "Soupe aux raviolis de feuilles de tofu au porc",
        "Riz pilaf aux champignons sauvages": "Riz pilaf aux champignons sauvages",
        "Riz nature": "Riz nature",
        "Raviolis (frit) au porc et chou": "Raviolis (frit) au porc et chou",
        "Soupe de wontons (porc et crevettes)": "Soupe de wontons (porc et crevettes)",
        "Gâteau de riz gluant sauté (bœuf, poulet, légumes, fruits de mer +2€)": "Gâteau de riz gluant sauté (bœuf, poulet, légumes, fruits de mer +2€)"
    },
    en: {
        "Plats principaux": "Main Courses",
        "Fondue": "Fondue",
        "Menu Midi": "Lunch Menu",
        "Tous": "All",
        "Poissons": "Fish",
        "Viandes": "Meats",
        "Légumes": "Vegetables",
        "Soupes": "Soups",
        "Riz": "Rice",
        "Poissons & Fruits de Mer": "Fish & Seafood",
        "Viandes & Volaille": "Meats & Poultry",
        "Légumes & Tofu": "Vegetables & Tofu",
        "Soupes & Nouilles": "Soups & Noodles",
        "Riz & Raviolis": "Rice & Dumplings",
        "Bar grillé à la sauce piquante": "Spicy grilled sea bass",
        "Choucroute de poisson": "Fish with pickled cabbage",
        "Intestins et poisson": "Fish with intestines",
        "Poisson bouilli au piment et poivre": "Fish boiled with chili and pepper",
        "Crevettes épicées": "Spicy shrimps",
        "Couteaux de mer à l'huile d'oignons verts": "Razor clams with scallion oil",
        "Calamars et crevettes au sel et poivre": "Salt and pepper squid with shrimp",
        "Calamars sautés avec légumes": "Stir-fried squid with vegetables",
        "Cuisses de poulet entières grillées": "Whole grilled chicken legs",
        "Marmite de bœuf": "Sichuan boiled beef",
        "Spécialité de Sichuan (épicé)": "Sichuan specialty (spicy)",
        "Pieds de cochon braisés": "Braised pork feet",
        "Pot de tendon de bœuf": "Braised beef tendon",
        "Pot d'agneau": "Lamb hot pot",
        "Porc frit à la sauce aigre-douce": "Sweet and sour pork",
        "Intestins de porc au piment fort": "Spicy pork intestines",
        "Porc déchiqueté à la sauce d'ail": "Shredded pork with garlic sauce",
        "Poulet épicé": "Spicy chicken",
        "Poulet sauce aigre-douce": "Sweet and sour chicken",
        "Assortiment de légumes du marché": "Seasonal vegetable assortment",
        "Mapo Tofu (épicé)": "Mapo Tofu (spicy)",
        "Aubergine à l'ail": "Eggplant with garlic sauce",
        "Feuilles de tofu au poivre": "Peppered tofu sheets",
        "Zizania avec porc": "Zizania with pork",
        "Luffa avec edamames": "Luffa with edamame",
        "Chou blanc sauté": "Stir-fried cabbage",
        "Haricots verts sautés": "Dry-fried green beans",
        "Mala Tang (bœuf, agneau, légumes et viandes épicés)": "Mala Tang (spicy beef, lamb and vegetables)",
        "Soupe pékinoise": "Peking hot and sour soup",
        "Soupe aux tomates et aux œufs": "Tomato and egg soup",
        "Soupe aux raviolis de feuilles de tofu au porc": "Tofu skin pork dumpling soup",
        "Riz pilaf aux champignons sauvages": "Wild mushroom pilaf rice",
        "Riz nature": "Steamed rice",
        "Raviolis (frit) au porc et chou": "Fried pork and cabbage dumplings",
        "Soupe de wontons (porc et crevettes)": "Wonton soup (pork and shrimp)",
        "Gâteau de riz gluant sauté (bœuf, poulet, légumes, fruits de mer +2€)": "Stir-fried glutinous rice cake (beef, chicken, vegetables, seafood +€2)"
    },
    zh: {
        "Plats principaux": "主菜",
        "Fondue": "火锅",
        "Menu Midi": "午餐菜单",
        "Tous": "全部",
        "Poissons": "鱼类",
        "Viandes": "肉类",
        "Légumes": "蔬菜",
        "Soupes": "汤类",
        "Riz": "米饭",
        "Poissons & Fruits de Mer": "海鲜类",
        "Viandes & Volaille": "肉类和家禽",
        "Légumes & Tofu": "蔬菜和豆腐",
        "Soupes & Nouilles": "汤和面条",
        "Riz & Raviolis": "米饭和饺子",
        "Bar grillé à la sauce piquante": "香辣烤鲈鱼",
        "Choucroute de poisson": "酸菜鱼",
        "Intestins et poisson": "鱼杂",
        "Poisson bouilli au piment et poivre": "水煮鱼",
        "Crevettes épicées": "香辣虾",
        "Couteaux de mer à l'huile d'oignons verts": "葱油蛏子",
        "Calamars et crevettes au sel et poivre": "椒盐鱿鱼虾",
        "Calamars sautés avec légumes": "蔬菜炒鱿鱼",
        "Cuisses de poulet entières grillées": "烤全鸡腿",
        "Marmite de bœuf": "水煮牛肉",
        "Spécialité de Sichuan (épicé)": "四川特色菜(辣)",
        "Pieds de cochon braisés": "红烧猪蹄",
        "Pot de tendon de bœuf": "红烧牛筋",
        "Pot d'agneau": "羊肉锅",
        "Porc frit à la sauce aigre-douce": "咕咾肉",
        "Intestins de porc au piment fort": "火爆肥肠",
        "Porc déchiqueté à la sauce d'ail": "蒜泥白肉",
        "Poulet épicé": "辣子鸡",
        "Poulet sauce aigre-douce": "糖醋鸡",
        "Assortiment de légumes du marché": "时令蔬菜拼盘",
        "Mapo Tofu (épicé)": "麻婆豆腐(辣)",
        "Aubergine à l'ail": "鱼香茄子",
        "Feuilles de tofu au poivre": "椒油豆腐皮",
        "Zizania avec porc": "茭白炒肉",
        "Luffa avec edamames": "丝瓜毛豆",
        "Chou blanc sauté": "手撕包菜",
        "Haricots verts sautés": "干煸四季豆",
        "Mala Tang (bœuf, agneau, légumes et viandes épicés)": "麻辣烫(辣味牛羊肉和蔬菜)",
        "Soupe pékinoise": "酸辣汤",
        "Soupe aux tomates et aux œufs": "番茄蛋汤",
        "Soupe aux raviolis de feuilles de tofu au porc": "千张包肉汤",
        "Riz pilaf aux champignons sauvages": "野生菌菇炒饭",
        "Riz nature": "白米饭",
        "Raviolis (frit) au porc et chou": "猪肉白菜煎饺",
        "Soupe de wontons (porc et crevettes)": "鲜虾馄饨汤",
        "Gâteau de riz gluant sauté (bœuf, poulet, légumes, fruits de mer +2€)": "炒年糕(牛肉/鸡肉/蔬菜/海鲜+2€)"
    }
};